#cspell:ignore buildx
name: Build and Push Docker image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    environment: build
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/emergency-contacts-print-qr:latest
          # Pass actual secrets needed during build
          secrets: |
            redis_password=${{ secrets.REDIS_PASSWORD }}
            fb_project_id=${{ secrets.FB_PROJECT_ID }}
            fb_client_email=${{ secrets.FB_CLIENT_EMAIL }}
            fb_private_key=${{ secrets.FB_PRIVATE_KEY }}
          # Pass non-sensitive config as build arguments from environment variables
          build-args: |
            DOMAIN=${{ vars.DOMAIN }}
